### ISSUE TITLE
java.lang.NoClassDefFoundError: com/google/common/base/Preconditions

### ISSUE THREAD

**Issue by GHrw62** [Simmetrics/simmetrics#27]
Trying to run an example with StringMetric cosineSimilarity when it gets a runtime exception about a missing dependency.  Nothing on the project page say anything about a requirement for this.   Can you update the Maven dependency to include this?

Makes it difficult to use this library otherwise.

`StackTrace:
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/base/Preconditions
	at org.simmetrics.builders.StringMetricBuilder$CompositeCollectionMetricBuilder.<init>(StringMetricBuilder.java:367)
	at org.simmetrics.builders.StringMetricBuilder$CompositeMultisetMetricBuilder.<init>(StringMetricBuilder.java:520)
	at org.simmetrics.builders.StringMetricBuilder.with(StringMetricBuilder.java:115)
	at org.simmetrics.metrics.StringMetrics.cosineSimilarity(StringMetrics.java:63)
`

**Comment by mpkorstanje** [comment]
The dependency on Guava and all other dependencies are listed in the [pom file](https://github.com/Simmetrics/simmetrics/blob/master/simmetrics-core/pom.xml#L18). Could you provide some steps to reproduce this issue?
